spring:
  security:
    filter:
      order: -100
#      security的filter优先级为-100
    jwt:
      key: abcdefghijk
      expire: 1
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: cyt238521cyt
    driver-class-name: com.mysql.cj.jdbc.Driver