spring:
  security:
    jwt:
      key: abcdefghijk
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: cyt238521cyt
    driver-class-name: com.mysql.cj.jdbc.Driver