spring:
  mail:
    host: smtp.163.com
    username: 18090958048@163.com
    password: VZXGIDBPFAYQOPBB
    default-encoding: UTF-8
    nickname: xiao菜的测试网站
  rabbitmq:
#    port: 5672
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
#    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
#    publisher-confirm-type: correlated
#    #保证交换机能把消息推送到队列中
#    publisher-returns: true
#    #这个配置是保证消费者会消费消息，手动确认
#    listener:
#      simple:
#        acknowledge-mode: manual
  security:
    filter:
      order: -100
#      security的filter优先级为-100
    jwt:
      key: abcdefghijk
      expire: 1
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: cyt238521cyt
    driver-class-name: com.mysql.cj.jdbc.Driver
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minio'
    password: '12345678'
  weather:
    key: 60fe141136c34a2a845d51ecb9530ff3